services:
  uptime-kuma:
    image: louislam/uptime-kuma:1-debian
    restart: unless-stopped
    volumes:
      - uptime-kuma:/app/data
    networks:
      - public-web

volumes:
  uptime-kuma:
    external: true

networks:
  public-web:
    external: true